<p class='d-flex justify-content-center ml-5 mr-5'><b>Définition du Périscolaire :</b></p>
<p class='d-flex justify-content-center ml-5 mr-5'>Il s’agit des heures d’accueil qui précèdent et suivent la classe, durant lesquelles un encadrement est proposé aux enfants scolarisés. Ce service est destiné aux St Justois.</p>
<p class='d-flex justify-content-center ml-5 mr-5'><b>Environnement :</b></p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Accueil à l’Îlot z’enfants d’élèves de 3 à 12 ans scolarisés et domiciliés à St Just</p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Les animateurs emmènent les enfants à (où de) l’école, soit à pieds, soit au moyen des deux minibus de la ville</p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Ils ont également la possibilité de faire leurs devoirs de 17h00 à 18h00 / 18h15 (après le temps du goûter), pour ensuite se diriger vers les activités diverses : jeux de société, lecture, sports collectifs… Différents jeux sont proposés aux enfants le matin et en fin de journée</p>
<p class='d-flex justify-content-center ml-5 mr-5'><b>Tarifs :</b></p>
<p class='d-flex justify-content-center ml-5 mr-5'>Tarif déterminé en fonction du dernier avis d’imposition, paiement sous 15 jours à réception de la facture. Paiement à l’heure, toute heure entamée est due.</p>
<p class='d-flex justify-content-center ml-5 mr-5'>Mercredi Horaires : 7h00-19h30 </p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Accueil échelonné de 7h00 à 9h30</p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Départ pour la maison ou la cantine à 12h00</p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Accueil échelonné de 13h30 à 14h00</p>
<p class='d-flex justify-content-center ml-5 mr-5'>- Départ échelonné de 17h00 à 19h30</p>
